apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  labels:
    app: hello-world
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-world
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - image: gcr.io/google-samples/hello-app:1.0
          name: hello
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 4m
---
# Docs:
# https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#session_affinity

apiVersion: v1
kind: Service
metadata:
  name: hello-world
  annotations:
    cloud.google.com/backend-config: '{"default": "hello-world"}'
spec:
  type: ClusterIP # Needs to be ClusterIP or LoadBalancer
  selector:
    app: hello-world
  ports:
    - port: 80
      targetPort: 8080
